//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.21 at 04:29:48 PM MST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "ecommerce/soap/Transactions", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ecommerce.soap.transactions;
